### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'fps'

### ISSUE THREAD

**Issue by tmashos** [fangfufu/Linux-Fake-Background-Webcam#36]
I'm getting this error when running the program. I've tried both manual and via docker compose. I've included the logs and my docker compose file below.

```
$ docker-compose up
Starting linux-fake-background-webcam_bodypix_1 ... done
Recreating linux-fake-background-webcam_fakecam_1 ... done
Attaching to linux-fake-background-webcam_bodypix_1, linux-fake-background-webcam_fakecam_1
bodypix_1  | 2020-05-27 17:35:14.481877: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
bodypix_1  | 2020-05-27 17:35:14.493556: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100940000 Hz
bodypix_1  | 2020-05-27 17:35:14.493897: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6faad80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
bodypix_1  | 2020-05-27 17:35:14.493920: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 273, in <module>
fakecam_1  |     main()
fakecam_1  |   File "fake.py", line 250, in main
fakecam_1  |     fps=args.fps,
fakecam_1  | AttributeError: 'Namespace' object has no attribute 'fps'
linux-fake-background-webcam_fakecam_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping linux-fake-background-webcam_bodypix_1   ... done
```

```
version: '3'
services:
    bodypix:
        image: bodypix
        build:
            context: ./bodypix
        read_only: true

    fakecam:
        image: fakecam
        build:
            context: ./fakecam
        read_only: true
        volumes:
          - /home/thomas/Pictures/camera-background/background.jpg:/src/background.jpg:ro
          - /home/thomas/Pictures/camera-background/foreground.jpg:/src/foreground.jpg:ro
          - /home/thomas/Pictures/camera-background/foreground-mask.png:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - /dev/video2:/dev/video2
            # output (virtual webcam)
            - /dev/video4:/dev/video4
        depends_on:
            - bodypix
        entrypoint: [ 'python3', '-u', 'fake.py', '-b', 'http://bodypix:9000/']
```
