### ISSUE TITLE
docker-compose error on akvcam

### ISSUE THREAD

**Issue by ManuLinares** [fangfufu/Linux-Fake-Background-Webcam#43]
I'm not using akvcam, i'm using v4l2loopback

```
Starting linux-fake-background-webcam_bodypix_1 ... done
Starting linux-fake-background-webcam_fakecam_1 ... done
Attaching to linux-fake-background-webcam_bodypix_1, linux-fake-background-webcam_fakecam_1
bodypix_1  | 2020-06-08 05:02:52.808669: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
bodypix_1  | 2020-06-08 05:02:52.884177: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3293975000 Hz
bodypix_1  | 2020-06-08 05:02:52.884603: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5d3c250 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
bodypix_1  | 2020-06-08 05:02:52.884633: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 22, in <module>
fakecam_1  |     from akvcam import AkvCameraWriter
fakecam_1  | ModuleNotFoundError: No module named 'akvcam'
linux-fake-background-webcam_fakecam_1 exited with code 1

```

**Comment by fangfufu** [comment]
fixed in 020e09b9433edab65c38d061469fd4b3f547cf37

**Comment by ManuLinares** [comment]
One fix, but another bug.  hardcoded  /dev/video2 ?

```
fakecam_1  | Cannot set camera property 3 to 1280, used value: 0.0
fakecam_1  | Cannot set camera property 4 to 720, used value: 0.0
fakecam_1  | Cannot set camera property 5 to 30, used value: 0.0
fakecam_1  | 
fakecam_1  | --- Make sure the v4l2loopback kernel module is loaded ---
fakecam_1  | sudo modprobe v4l2loopback devices=1
fakecam_1  | 
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 362, in <module>
fakecam_1  |     main()
fakecam_1  |   File "fake.py", line 336, in main
fakecam_1  |     cam = FakeCam(
fakecam_1  |   File "fake.py", line 113, in __init__
fakecam_1  |     self.fake_cam = pyfakewebcam.FakeWebcam(v4l2loopback_path, self.width, self.height)
fakecam_1  |   File "/usr/local/lib/python3.8/dist-packages/pyfakewebcam/pyfakewebcam.py", line 31, in __init__
fakecam_1  |     raise FileNotFoundError('device does not exist: {}'.format(video_device))
fakecam_1  | FileNotFoundError: device does not exist: /dev/video2
linux-fake-background-webcam_fakecam_1 exited with code 1

```

**Comment by fangfufu** [comment]
Please refer to 
https://github.com/fangfufu/Linux-Fake-Background-Webcam/blob/master/DOCKER.md

**Comment by ManuLinares** [comment]
/dev/video10 is the input camera(my face)

/dev/video0 is the output for fake cam

created with **"sudo modprobe v4l2loopback devices=2  exclusive_caps=1 video_nr=10 card_label="fakeCam" max_buffers=8"** 


docker-compose.yml
```
version: '3'
services:
    bodypix:
        image: bodypix
        build:
            context: ./bodypix
        read_only: true

    fakecam:
        image: fakecam
        build:
            context: ./fakecam
        read_only: true
        volumes:
            - /home/user/Pictures/background.png:/src/background.jpg:ro
        #   - /path/to/foreground.jpg:/src/foreground.jpg:ro
        #   - /path/to/foreground-mask.png:/src/foreground-mask.png:ro
        devices:
            # input (webcam)
            - /dev/video10:/dev/video10
            # output (virtual webcam)
            - /dev/video0:/dev/video0
        depends_on:
            - bodypix
        entrypoint: [ 'python3', '-u', 'fake.py', '-B', 'http://bodypix:9000/']

```
