### ISSUE TITLE
docker akvcam not working

### ISSUE THREAD

**Issue by jslim89** [fangfufu/Linux-Fake-Background-Webcam#64]
I'm using built-in webcam

I got this error

```
fakecam_1  | Cannot set camera property 3 to 1280, used value: 640.0
fakecam_1  | Cannot set camera property 5 to 30, used value: 10.0
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "fake.py", line 397, in <module>
fakecam_1  |     main()
fakecam_1  |   File "fake.py", line 368, in main
fakecam_1  |     cam = FakeCam(
fakecam_1  |   File "fake.py", line 120, in __init__
fakecam_1  |     self.fake_cam = AkvCameraWriter(v4l2loopback_path, self.width, self.height)
fakecam_1  |   File "/src/akvcam.py", line 14, in __init__
fakecam_1  |     self.d = self.open_camera()
fakecam_1  |   File "/src/akvcam.py", line 30, in open_camera
fakecam_1  |     ioctl(d, v4l2.VIDIOC_S_FMT, vid_format)
fakecam_1  | OSError: [Errno 22] Invalid argument
fakecam_1  | Exception ignored in: <function AkvCameraWriter.__del__ at 0x7f1bb007e5e0>
fakecam_1  | Traceback (most recent call last):
fakecam_1  |   File "/src/akvcam.py", line 48, in __del__
fakecam_1  |     self.queue.put(None)
fakecam_1  | AttributeError: 'AkvCameraWriter' object has no attribute 'queue'
```

Here's my docker-compose.yml

```
  version: '3'                                                                                                                                                        
  services:                                                                                                                                                           
      bodypix:                                                                                                                                                        
          image: bodypix                                                                                                                                              
          build:                                                                                                                                                      
              context: ./bodypix                                                                                                                                      
          read_only: true                                                                                                                                             
                                                                                                                                                                      
      fakecam:                                                                                                                                                        
          image: fakecam                                                                                                                                              
          build:                                                                                                                                                      
              context: ./fakecam                                                                                                                                      
          read_only: true                                                                                                                                             
          volumes:                                                                                                                                                    
           - ./fakecam/background.jpg:/src/background.jpg:ro                                                                                                         
           - ./fakecam/foreground.jpg:/src/foreground.jpg:ro                                                                                                         
           - ./fakecam/foreground-mask.png:/src/foreground-mask.png:ro                                                                                               
          devices:                                                                                                                                                    
              # input (webcam)                                                                                                                                        
             - /dev/video0:/dev/video0                                                                                                                               
              # output (virtual webcam)                                                                                                                               
             - /dev/video1:/dev/video2                                                                                                                               
          depends_on:                                                                                                                                                 
              - bodypix                                                                                                                                               
         entrypoint: [ 'python3', '-u', 'fake.py', '-v', '/dev/video2', '-B', 'http://bodypix:9000/', "--no-foreground", '--akvcam']
```

My device

```
$ ls -ltrh /dev/video*
crw-rw----+ 1 root video 81, 1 Oct 21 07:25 /dev/video1
crw-rw----+ 1 root video 81, 0 Oct 21 07:25 /dev/video0
```

And I follow your instruction to install avkcam using DKMS

What am I missing here? 🤔️
